### ISSUE TITLE
L'extension ne fonctionne pas

### ISSUE THREAD

**Issue by galapgos** [candiceetdefondouze/dysclusif#1]
Salut, merci pour la mise à disposition de cette extension sur Thunderbird, cependant, celle-ci ne fonctionne pas.
Aucun mail n'est modifié (malgré un tentative en "Texte seul". 

Je suis sous Thunderbird 115.6.1.

**Comment by candiceetdefondouze** [comment]
Bonjour,

L'extension a un paramètre pour pouvoir la désactiver temporairement. Maladroitement, j'ai mis celui-ci actif par défaut. Je vais corriger cela, mais en attendant, voici ce que vous pouvez faire:

Ouvrir le popup en haut à droite de Thunderbird
![20240119_1617-7912](https://github.com/candiceetdefondouze/dysclusif/assets/127240585/df7f17ba-a2c9-4e3c-bd59-518daab3fdd8)


Cliquer sur le "•e•s" pour activer l'extension (ce n'est pas très intuitif, je le conçois)
![20240119_1617-6752](https://github.com/candiceetdefondouze/dysclusif/assets/127240585/4c7262e7-3aed-426b-88a7-dbc63fd00087)

Ré-ouvrez le mail que vous étiez en train de consulter, cela devrait fonctionner, au moins sur les formes les plus courantes. Si il y a des mots qui ne sont pas détectés, ouvrez une autre issue pour m'en notifier.

Bonne journée
(Faites moi savoir si cela a résolu le problème)

**Comment by galapgos** [comment]
Yes, cela a bien résolu le problème ! Merci beaucoup pour cette réponse ultra rapide.

**Comment by galapgos** [comment]
Yes, cela a bien résolu le problème ! Merci beaucoup pour cette réponse ultra rapide.
